version: "3.8"
services:
  mongodb:
    image: 'goal-node'
    volumes:
      - data:data/db
    env_file:
      - env/mongo.env
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb
  # frontend
